/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface EscrowVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "domainSeparator"
      | "fundDeal"
      | "getDeal"
      | "refundAfterTimeout"
      | "settleDeal"
      | "settlementDigest"
      | "settlementNonces"
      | "verifier"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "DealFunded" | "DealRefunded" | "DealSettled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "domainSeparator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fundDeal",
    values: [BytesLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getDeal", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "refundAfterTimeout",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settleDeal",
    values: [BytesLike, boolean, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settlementDigest",
    values: [BytesLike, boolean, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settlementNonces",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "domainSeparator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fundDeal", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getDeal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "refundAfterTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "settleDeal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "settlementDigest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settlementNonces",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;
}

export namespace DealFundedEvent {
  export type InputTuple = [
    dealHash: BytesLike,
    payer: AddressLike,
    amount: BigNumberish,
    recipientIfTrue: AddressLike,
    recipientIfFalse: AddressLike,
    timeout: BigNumberish
  ];
  export type OutputTuple = [
    dealHash: string,
    payer: string,
    amount: bigint,
    recipientIfTrue: string,
    recipientIfFalse: string,
    timeout: bigint
  ];
  export interface OutputObject {
    dealHash: string;
    payer: string;
    amount: bigint;
    recipientIfTrue: string;
    recipientIfFalse: string;
    timeout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DealRefundedEvent {
  export type InputTuple = [
    dealHash: BytesLike,
    payer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [dealHash: string, payer: string, amount: bigint];
  export interface OutputObject {
    dealHash: string;
    payer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DealSettledEvent {
  export type InputTuple = [
    dealHash: BytesLike,
    verdict: boolean,
    recipient: AddressLike,
    amount: BigNumberish,
    attestationHash: BytesLike,
    nonce: BigNumberish
  ];
  export type OutputTuple = [
    dealHash: string,
    verdict: boolean,
    recipient: string,
    amount: bigint,
    attestationHash: string,
    nonce: bigint
  ];
  export interface OutputObject {
    dealHash: string;
    verdict: boolean;
    recipient: string;
    amount: bigint;
    attestationHash: string;
    nonce: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EscrowVault extends BaseContract {
  connect(runner?: ContractRunner | null): EscrowVault;
  waitForDeployment(): Promise<this>;

  interface: EscrowVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  domainSeparator: TypedContractMethod<[], [string], "view">;

  fundDeal: TypedContractMethod<
    [
      dealHash: BytesLike,
      recipientIfTrue: AddressLike,
      recipientIfFalse: AddressLike,
      timeout: BigNumberish
    ],
    [void],
    "payable"
  >;

  getDeal: TypedContractMethod<
    [dealHash: BytesLike],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        boolean,
        boolean,
        boolean,
        boolean,
        bigint,
        string,
        bigint
      ] & {
        amount: bigint;
        payer: string;
        recipientIfTrue: string;
        recipientIfFalse: string;
        timeout: bigint;
        funded: boolean;
        settled: boolean;
        refunded: boolean;
        releasedToTrue: boolean;
        settledAmount: bigint;
        attestationHash: string;
        nonce: bigint;
      }
    ],
    "view"
  >;

  refundAfterTimeout: TypedContractMethod<
    [dealHash: BytesLike],
    [void],
    "nonpayable"
  >;

  settleDeal: TypedContractMethod<
    [
      dealHash: BytesLike,
      verdict: boolean,
      attestationHash: BytesLike,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  settlementDigest: TypedContractMethod<
    [
      dealHash: BytesLike,
      verdict: boolean,
      attestationHash: BytesLike,
      nonce: BigNumberish
    ],
    [string],
    "view"
  >;

  settlementNonces: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  verifier: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "domainSeparator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fundDeal"
  ): TypedContractMethod<
    [
      dealHash: BytesLike,
      recipientIfTrue: AddressLike,
      recipientIfFalse: AddressLike,
      timeout: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getDeal"
  ): TypedContractMethod<
    [dealHash: BytesLike],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        boolean,
        boolean,
        boolean,
        boolean,
        bigint,
        string,
        bigint
      ] & {
        amount: bigint;
        payer: string;
        recipientIfTrue: string;
        recipientIfFalse: string;
        timeout: bigint;
        funded: boolean;
        settled: boolean;
        refunded: boolean;
        releasedToTrue: boolean;
        settledAmount: bigint;
        attestationHash: string;
        nonce: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "refundAfterTimeout"
  ): TypedContractMethod<[dealHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settleDeal"
  ): TypedContractMethod<
    [
      dealHash: BytesLike,
      verdict: boolean,
      attestationHash: BytesLike,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settlementDigest"
  ): TypedContractMethod<
    [
      dealHash: BytesLike,
      verdict: boolean,
      attestationHash: BytesLike,
      nonce: BigNumberish
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "settlementNonces"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "verifier"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "DealFunded"
  ): TypedContractEvent<
    DealFundedEvent.InputTuple,
    DealFundedEvent.OutputTuple,
    DealFundedEvent.OutputObject
  >;
  getEvent(
    key: "DealRefunded"
  ): TypedContractEvent<
    DealRefundedEvent.InputTuple,
    DealRefundedEvent.OutputTuple,
    DealRefundedEvent.OutputObject
  >;
  getEvent(
    key: "DealSettled"
  ): TypedContractEvent<
    DealSettledEvent.InputTuple,
    DealSettledEvent.OutputTuple,
    DealSettledEvent.OutputObject
  >;

  filters: {
    "DealFunded(bytes32,address,uint256,address,address,uint64)": TypedContractEvent<
      DealFundedEvent.InputTuple,
      DealFundedEvent.OutputTuple,
      DealFundedEvent.OutputObject
    >;
    DealFunded: TypedContractEvent<
      DealFundedEvent.InputTuple,
      DealFundedEvent.OutputTuple,
      DealFundedEvent.OutputObject
    >;

    "DealRefunded(bytes32,address,uint256)": TypedContractEvent<
      DealRefundedEvent.InputTuple,
      DealRefundedEvent.OutputTuple,
      DealRefundedEvent.OutputObject
    >;
    DealRefunded: TypedContractEvent<
      DealRefundedEvent.InputTuple,
      DealRefundedEvent.OutputTuple,
      DealRefundedEvent.OutputObject
    >;

    "DealSettled(bytes32,bool,address,uint256,bytes32,uint256)": TypedContractEvent<
      DealSettledEvent.InputTuple,
      DealSettledEvent.OutputTuple,
      DealSettledEvent.OutputObject
    >;
    DealSettled: TypedContractEvent<
      DealSettledEvent.InputTuple,
      DealSettledEvent.OutputTuple,
      DealSettledEvent.OutputObject
    >;
  };
}
